logging_base: "/homes/pr450/repos/research_projects/error_modelling_torus/results_link/postbudapest2/model_recovery/mcmaster2022_e2_dircue_cue_AR2/est_dim_von_mises_and_uniform/recovering_delobed_remove_init_min_seps"
run_name: run
synthetic_data_code: delobed_remove
synthetic_data_root: "/homes/pr450/repos/research_projects/error_modelling_torus/results_link/postbudapest2/trained_on_data/mcmaster2022_e2_dircue_cue_AR2/est_dim_von_mises_and_uniform"
dataset_name: cross_model_fit
underlying_dataset: mcmaster2022_e2_dircue
init_min_seps: true
R_per_dim: 36
fix_inducing_point_locations: true
kernel_type: weiland
# kernel_type: exp_cos
# inducing_point_variational_parameterisation_type: vanilla
defaults_paths:
- /homes/pr450/repos/all_utils/purias_utils/error_modelling_torus/non_parametric_error_model/default_bnp_and_training_params.yaml
- /homes/pr450/repos/research_projects/error_modelling_torus/non_parametric_model/commands/a_trained_on_data/configs/mcmaster2022_e2_dircue_est_dim_von_mises.yaml

